module.exports = {
  album: require('../routes/album'),
  comment: require('../routes/comment'),
  feedback: require('../routes/feedback'),
  lyric: require('../routes/lyric'),
  mv: require('../routes/mv'),
  new: require('../routes/new'),
  radio: require('../routes/radio'),
  recommend: require('../routes/recommend'),
  search: require('../routes/search'),
  singer: require('../routes/singer'),
  song: require('../routes/song'),
  songlist: require('../routes/songlist'),
  test: require('../routes/test'),
  top: require('../routes/top'),
  user: require('../routes/user'),
  vkey: require('../routes/vkey'),
}
